### ISSUE TITLE
Implement Error Handling Module

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#80] opened 2024-10-23 08:54 UTC
Task: Create a dedicated error handling module for the land_registry. Define custom errors for all possible failure scenarios in the land registry and NFT contracts.

Definition of Done:
•  A new file errors.cairo is created with all custom errors defined.
•  All contracts use the new error module instead of generic assert statements.

Note: Only applications through the OnlyDust platform will be considered.

**Comment by Jemiiah** [comment] 2024-10-23 08:56
@fishonamos I would love to work on this issue

**Comment by Mystic-Nayy** [comment] 2024-10-23 08:57
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a web3/frontend developer

### How I plan on tackling this issue
I will create an `errors.cairo` file with custom error definitions for all failure scenarios in the land registry and NFT contracts. Update all contracts to use these custom errors instead of generic assertions.

**Comment by martinvibes** [comment] 2024-10-23 13:37
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello @fishonamos I'm a frontend d3v and a blockchain dev I would like to work on this issue :) this will be my first time contributing on this project if I'm assigned
Please kindly assign :)



### How I plan on tackling this issue
I will read and understand the issue carefully and I'll implement the required change 
I will create an errors.cairo file with custom error definitions for all failure scenarios in the land registry and NFT contracts. Update all contracts to use these custom errors instead of generic assertions.

**Comment by CollinsC1O** [comment] 2024-10-23 18:29
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer. I will love to solve this issue. I can handle this

**Comment by MullerTheScientist** [comment] 2024-10-23 23:39
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue

i will Define custom errors for specific failure scenarios.
Use ErrorCode variants for generic errors.
Implement error handling in contracts using Result types.
Test error scenarios thoroughly.

**Comment by josephchimebuka** [comment] 2024-10-24 01:44
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. 

### How I plan on tackling this issue
I will ensure that the description for this issue is met

**Comment by Benjtalkshow** [comment] 2024-10-24 08:05
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To implement the error handling module for the land_registry, I will create a new file named errors.cairo that will define custom error messages for all potential failure scenarios in both the land registry and NFT contracts. This module will help improve the clarity and maintainability of the code by providing specific error messages rather than using generic assert statements.

Once the error module is created, I will ensure that all relevant contracts are updated to utilize this new error handling system. This will involve replacing existing assert statements with calls to the appropriate custom errors defined in the errors.cairo file.

The task will be considered complete when the error module is implemented, all custom errors are defined, and the contracts are successfully integrated with the new error handling system.

**Comment by 0xdevcollins** [comment] 2024-10-24 08:26
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
I'll create a dedicated errors.cairo module for the land_registry, defining custom errors tailored to every potential failure scenario in the land registry and NFT contracts. These custom errors will replace generic assert statements across all contracts, ensuring more precise and meaningful error handling.

**Comment by od-hunter** [comment] 2024-10-24 08:27
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

### How I plan on tackling this issue
To solve this issue, I’ll take the following the steps:
1.⁠ ⁠I’ll define a new error handling module to contain all custom errors.
2.⁠ ⁠I’ll include specific errors for all possible failure scenarios relevant to the land registry and NFT contracts.
3.⁠ ⁠Next, I’ll update existing contracts to use the new error module instead of generic assertions.
4.⁠ ⁠Lastly, I’ll horoughly test the contracts to ensure that custom errors are triggered appropriately in error scenarios.

Please assign me, I’m ready to work.

**Comment by jaiminRaiyani** [comment] 2024-10-24 09:09
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a software engineer with a strong foundation in computer engineering, specializing in full-stack development and blockchain technologies. My expertise includes working with various programming languages such as JavaScript, C++, and Node.js, along with experience in developing smart contracts on blockchain platforms. I have successfully completed projects that involve building secure applications, integrating different wallet systems, and ensuring code quality through robust error handling and testing practices.

My experience in building and maintaining complex systems enables me to understand the importance of clear error handling in smart contracts. By defining custom errors, I can enhance user experience, improve code maintainability, and provide clearer debugging information, which is crucial in decentralized applications where transactions can fail for numerous reasons.

### How I plan on tackling this issue
To create a dedicated error handling module for the land registry, I would approach the task in the following manner:

Requirements Gathering:

Identify all potential failure scenarios within the land registry and NFT contracts. This would include scenarios such as invalid land IDs, unauthorized access, insufficient funds, and cases where land already exists.
Define Custom Errors:

Create a new file errors.cairo where I will define custom error codes for each failure scenario. I would ensure that each error has a clear and meaningful description, which would aid in debugging and improve the overall clarity of the code.
Refactor Contracts:

Systematically update all existing contracts to replace generic assert statements with the defined custom errors. I would ensure that every contract function properly utilizes the new error module, maintaining consistency across the project.
Testing and Validation:

Develop comprehensive test cases to validate the error handling functionality. This would include unit tests to ensure that each custom error is triggered under the correct conditions. I would leverage automated testing tools to run these tests efficiently.
Documentation:

Update the project documentation to include descriptions of all custom errors and their intended use cases. This would serve as a valuable resource for future developers and maintainers of the codebase.
Review and Feedback:

Conduct code reviews with peers to gather feedback on the implementation of the error handling module, ensuring that it meets project standards and expectations.

**Comment by saimeunt** [comment] 2024-10-24 09:44
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past

### How I plan on tackling this issue
I will carefully implement the error module as requested and I'll modify the codebase to use custom errors instead. I will make sure the tests are updated too.

ETA 1 day.

**Comment by ShantelPeters** [comment] 2024-10-24 10:22
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I have a solid foundation in smart contract development, particularly with Cairo, and extensive experience in creating robust, maintainable code. My background includes implementing best practices in error handling and defining custom error messages that enhance user experience and debugging capabilities. With my knowledge of the land registry and NFT contracts, I can effectively design an error handling module that addresses potential failure scenarios.



### How I plan on tackling this issue
o create a dedicated error handling module for the land registry, I will follow these steps:

Identify Failure Scenarios: I will begin by reviewing the existing land registry and NFT contracts to identify all potential failure scenarios that could occur during their execution. This will include issues like invalid input, unauthorized access, and state inconsistencies.

Define Custom Errors: I will create a new file named errors.cairo where I will define custom error types for each identified failure scenario. Each error will have a descriptive name and a brief explanation of the conditions under which it occurs, ensuring clarity and ease of use.

Implement Error Handling: I will refactor the existing contracts to replace generic assert statements with the newly defined custom error types. This will enhance the clarity of error reporting and allow for more informative feedback when failures occur.

Testing: I will conduct thorough testing to ensure that all error handling works as intended. This will involve simulating various failure scenarios to confirm that the appropriate custom error messages are triggered and that they provide useful information for debugging.

Documentation: Finally, I will document the new error handling module, including explanations of each custom error and guidelines for its use within the contracts. This documentation will facilitate future development and maintenance.

By implementing this approach, I aim to enhance the robustness and user-friendliness of the land registry and NFT contracts while ensuring that error handling is consistent and informative.

**Comment by caxtonacollins** [comment] 2024-10-24 11:19
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am applying to this issue via https://app.onlydust.com/p/landver

I am a fullstack developer worked with various frameworks over the years, i have been trying to contribute to various open source project over the years. currently i am transitioning into the web3 space.

### How I plan on tackling this issue
i will like to be assign to this issue.

**Closed** 2024-11-05 19:59 UTC
Labels: good first issue, ODHack9, Blocked
