### ISSUE TITLE
Add Custom Error Pages and Error Handling

### ISSUE THREAD

**Issue by GoSTEAN** [NoshonNetworks/landver#181] opened 2024-11-21 09:19 UTC
### Description 
We need to improve error handling by adding custom pages and catchers to provide a better user experience and align with the design guidelines.

### Tasks:

Create a custom 404 page that matches the design and provides navigation options for users.
Add a global Error page to handle unexpected errors with an option to retry actions.
Implement localized error catchers for specific routes where necessary.
Ensure all error pages are consistent with the overall design.
Set up error logging to help with debugging and tracking issues.

**Comment by 0xdevcollins** [comment] 2024-11-21 09:27
Hello @fishonamos Can I work on this?

I am a Full Stack Blockchain Developer with expertise in Next.js, TypeScript, React, Node.js, and Solidity/Rust. With 46 contributions across 10 OnlyDust projects, I bring technical excellence, adaptability, and a focus on user-centric blockchain solutions.

**Comment by mimisavage** [comment] 2024-11-21 09:30
I can ensure quality and timely delivery for this task. Can I work on it?

**Comment by Pvsaint** [comment] 2024-11-21 10:01
Hi Fishon please assign me this task, let me work on it sir.

**Comment by Tzienom** [comment] 2024-11-21 13:51
Hi, I'm Gabriel and I would love to work on this issue #181.

I do believe that I would be able to get the job done in 48 hours.

I will create a 404 error page that matches the remainder of the existing UI and ensure that it catches any error that might occur from an API fetch or any unforeseen event on any page. All router configurations will be updated to redirect undefined routes to this custom page, whilst logging the cause of the error to the console.

**Comment by abdegenius** [comment] 2024-11-21 14:02
Let me handle this issue!

**Comment by Steph3097** [comment] 2024-11-21 14:03
Hello! my name is Sttef and i have 5+ of experience in front-end development! 

Im part of the Dojo team ⛩️

I would like to be part of this issue, I will create the error page and make it fit perfectly with the design, add the global error page, log the errors and make sure that all pages fit the design! Can i give it a try? 

Thanks!

**Comment by Steph3097** [comment] 2024-11-21 14:03
Hello! my name is Sttef and i have 5+ of experience in front-end development! 

Im part of the Dojo team ⛩️

I would like to be part of this issue, I will create the error page and make it fit perfectly with the design, add the global error page, log the errors and make sure that all pages fit the design! Can i give it a try? 

Thanks!

**Comment by Steph3097** [comment] 2024-11-21 14:04
Hello! my name is Sttef and i have 5+ of experience in front-end development! 

Im part of the Dojo team ⛩️

I would like to be part of this issue, I will create the error page and make it fit perfectly with the design, add the global error page, log the errors and make sure that all pages fit the design! Can i give it a try? 

Thanks!

**Comment by Akshola00** [comment] 2024-11-21 14:11
May I pick this up?

**Comment by Awointa** [comment] 2024-11-21 14:20
Hi I am a react developer who is willing to take this task

**Comment by JosueBrenes** [comment] 2024-11-21 14:23
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member. ⛩️

I estimate this will take 1 day to complete.

## How I Would Resolve This

To improve error handling and align with the design guidelines, I would implement the following steps:

---

### 1. **Create a Custom 404 Page**
   - **Objective**: Provide a user-friendly experience for "Page Not Found" errors.
   - Design:
     - Use the project's existing design system (e.g., colors, fonts, layout).
     - Include a clear message, such as "Oops! This page doesn’t exist."
     - Add navigation options, such as a "Go Home" button and links to popular pages.
   - Implementation:
     ```jsx
     // pages/404.js
     export default function Custom404() {
       return (
         <div className="min-h-screen flex flex-col justify-center items-center bg-gray-100 text-center">
           <h1 className="text-4xl font-bold text-gray-800">404 - Page Not Found</h1>
           <p className="text-gray-600 my-4">Sorry, we couldn't find the page you're looking for.</p>
           <button
             className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
             onClick={() => window.location.href = '/'}
           >
             Go to Home
           </button>
         </div>
       );
     }
     ```

---

### 2. **Add a Global Error Page**
   - **Objective**: Handle unexpected errors with a friendly interface.
   - Design:
     - Display a message like "Something went wrong."
     - Include a retry button to reload the page or retry an action.
   - Implementation:
     ```jsx
     // pages/_error.js
     import { useRouter } from 'next/router';

     export default function GlobalError({ statusCode }) {
       const router = useRouter();

       return (
         <div className="min-h-screen flex flex-col justify-center items-center bg-gray-100 text-center">
           <h1 className="text-4xl font-bold text-gray-800">
             {statusCode ? `Error ${statusCode}` : "An unexpected error has occurred"}
           </h1>
           <p className="text-gray-600 my-4">We’re working to fix this issue. Please try again later.</p>
           <button
             className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
             onClick={() => router.reload()}
           >
             Retry
           </button>
         </div>
       );
     }

     GlobalError.getInitialProps = ({ res, err }) => {
       const statusCode = res ? res.statusCode : err ? err.statusCode : 404;
       return { statusCode };
     };
     ```

---

### 3. **Implement Localized Error Catchers**
   - **Objective**: Handle specific errors for routes or components (e.g., form submissions, API calls).
   - Approach:
     - Wrap routes or components with a try-catch mechanism.
     - Display localized error messages for specific scenarios.
   - Example for API error handling:
     ```jsx
     import { useState } from 'react';

     function SubmitForm() {
       const [error, setError] = useState(null);

       const handleSubmit = async () => {
         try {
           const response = await fetch('/api/submit', { method: 'POST' });
           if (!response.ok) throw new Error("Failed to submit data.");
           // Handle success
         } catch (err) {
           setError(err.message);
         }
       };

       return (
         <div>
           <button onClick={handleSubmit} className="bg-blue-500 text-white px-4 py-2 rounded">Submit</button>
           {error && <p className="text-red-500 mt-2">{error}</p>}
         </div>
       );
     }
     ```

---

### 4. **Ensure Consistency**
   - Follow design guidelines for all error pages:
     - Use the same typography, color palette, and spacing as the rest of the application.
     - Test responsiveness to ensure proper display on all devices.
   - Centralize shared styles and components for reuse across error pages.

---

### 5. **Set Up Error Logging**
   - Use a logging service (e.g., Sentry, LogRocket) to capture and track errors.
   - Add a centralized error handler in Next.js:
     ```javascript
     // _app.js
     import * as Sentry from "@sentry/react";

     Sentry.init({
       dsn: "your-sentry-dsn", // Replace with your Sentry DSN
     });

     function MyApp({ Component, pageProps }) {
       return <Component {...pageProps} />;
     }

     export default Sentry.withProfiler(MyApp);
     ```
   - Log localized errors in try-catch blocks for debugging:
     ```javascript
     catch (err) {
       Sentry.captureException(err);
       console.error(err);
     }
     ```

---

### 6. **Testing**
   - Simulate 404 errors by visiting non-existent routes.
   - Trigger global errors by simulating API failures or server crashes.
   - Test localized error messages for specific user actions.
   - Validate error page responsiveness and consistency across browsers.

---

### Deliverables:
   - A custom 404 page with navigation options.
   - A global error page with retry functionality.
   - Localized error catchers for specific routes and components.
   - Integrated error logging using a tool like Sentry.
   - Fully tested error handling flow.

---

**Comment by starknetbrother** [comment] 2024-11-21 14:35
Would love to tackle this!

**Comment by Villarley** [comment] 2024-11-21 14:42
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
I would follow all the guidelines and instructions to get exactly what you want. I already contribute to Landver so i'd be able to deliver faster thanks to my experience with the project. 
Pls feel free to reach out!

**Comment by Steph3097** [comment] 2024-11-21 14:43
Hello! my name is Sttef and i have 5+ of experience in front-end development! 

Im part of the Dojo team ⛩️

I would like to be part of this issue, I will create the error page and make it fit perfectly with the design, add the global error page, log the errors and make sure that all pages fit the design! Can i give it a try? 

Thanks!

**Comment by akintewe** [comment] 2024-11-21 14:45
Hello can i be assigned this issue, i am a new contributor with experience in Cario and javascript, would love to work on this , my ETA is >48 Hours and ill create a draft PR in 17 hours time. Thank you for this opportunity. :)

**Comment by Benjtalkshow** [comment] 2024-11-21 14:49
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by amJoe-dev** [comment] 2024-11-21 14:59
Mind if I try this one?

**Comment by austineblaise** [comment] 2024-11-21 15:05
This is my first time trying to work on an OnlyDust open-source project, and I’m excited to contribute! I can help by designing a user-friendly 404 page that matches the project’s design and provides easy navigation for users. I’ll also create a global error page to handle unexpected issues, giving users options to retry actions or return to a safe part of the app. Additionally, I can implement custom error handlers for specific parts of the app to ensure error messages are clear and relevant to the situation. To help with debugging, I’ll set up error logging to track and fix issues efficiently.

I’m eager to get started and learn from this experience. Let me know how I can begin contributing!.

**Comment by chibokaxavier** [comment] 2024-11-21 15:16
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. This would be my first time contibuting to this project and i would provide a solution by  creating a custom 404 page with clear navigation options like "Go Home" or "Back to Previous Page" to help users find their way. I’d also set up a global error page that displays a friendly message like "Oops, something went wrong" with a "Retry" button so users can try again. For specific pages or actions, I’d implement localized error catchers to show relevant messages. I’d ensure all error pages match the app’s design for a consistent user experience and set up error logging to track and debug issues easily. This way, users have a smooth experience, and I can quickly address any problems that arise.i would really love to be assigned this issue and work on this project.

**Comment by ShantelPeters** [comment] 2024-11-21 15:16
I'd love to work on this!

**Comment by Pvsaint** [comment] 2024-11-21 15:27
Hi I'm Victor, I'm a first time contributor, a frontend and smart contract developer. Please assign me this task, let me work on it sir.

**Comment by Kaminar-i** [comment] 2024-11-21 15:41
I would like to work on this issue. With my experience, i'm sure of satisfactory result

**Comment by Michaelkingsdev** [comment] 2024-11-21 15:45
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.  This is my first time contributing to this project.

**Comment by LeonM95** [comment] 2024-11-21 15:56
Hello,

My name is Leo, and I'm a junior software developer from Costa Rica. This will be my first Hackathon, and I am excited to apply for this issue.

I have experience working with C#, JavaScript, Node.js, TypeScript, HTML5, CSS3, I believe this issue will be a fantastic opportunity to enhance my coding/design skills.

Currently, I am also learning about Web3 technologies.

Thank you for considering my application.

Best regards,  
Leo

**Comment by Akshola00** [comment] 2024-11-21 16:11
Can I take this from here?
i would like to work on this

**Comment by melnikga** [comment] 2024-11-21 16:20
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by Amarjeet325** [comment] 2024-11-21 18:05
Hi , I am a proficient MERN stack developer with experience in full-stack development. I believe I can contribute effectively to this project. Could you kindly assign this issue/task to me?

**Comment by Yunusabdul38** [comment] 2024-11-21 18:08
I’d like to work on this,
and make sure it meets the requirements

**Comment by vestor-dev** [comment] 2024-11-21 18:32
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by JoelVR17** [comment] 2024-11-21 19:28
## I'm Joel Vargas, and I'm a Frontend Developer
## Dojo Coding 🔥

# Enhance Error Handling with Custom Pages

## Description
To improve the user experience and align with design guidelines, we need to implement custom error pages and localized error catchers. This ensures users are guided appropriately when errors occur.

---

## Tasks

### 1. **Custom 404 Page**
- Design and implement a custom 404 page that:
  - Matches the platform's design guidelines.
  - Includes a message indicating the page was not found.
  - Provides navigation options (e.g., buttons to return to the homepage or explore other sections).

### 2. **Global Error Page**
- Create a global error page for unexpected errors with:
  - A user-friendly message.
  - A "Retry" button to allow users to reattempt actions.
  - A fallback option to navigate back to the homepage.

### 3. **Localized Error Catchers**
- Identify routes that require localized error handling.
- Implement specific error handlers for these routes to:
  - Display contextual messages.
  - Offer actions tailored to the route (e.g., reload data, retry submission).

### 4. **Design Consistency**
- Ensure all error pages maintain the platform's branding and design consistency:
  - Use the same typography, color scheme, and layout standards.
  - Include any relevant UI components or assets from the design system.

### 5. **Error Logging**
- Set up error logging to capture and track issues:
  - Log errors in a centralized service (e.g., Sentry, LogRocket).
  - Include details such as the error type, affected routes, and user actions leading up to the error.

---

## Acceptance Criteria
- The custom 404 page is visually consistent and provides clear navigation options.
- The global error page offers actionable steps (e.g., retry, navigate to homepage).
- Localized error handlers are implemented for specific routes.
- All error pages match the platform's design and style.
- Errors are logged effectively for debugging and monitoring.

---

## Deliverables
- A functional 404 page and global error page.
- Localized error handling for designated routes.
- Consistent error page designs.
- Error logging integrated with the selected tracking tool.

---

### Additional Notes
For any clarifications on design or specific routes requiring localized handling, consult the design team or project manager.

**Comment by jedstroke** [comment] 2024-11-21 22:02
Can I be assigned to this?

**Comment by sandragcarrillo** [comment] 2024-11-22 00:50
I would love to contribute to this issue, I have experience as a frontend developer creating web3 and web3 websites.

**Comment by ekumamatthew** [comment] 2024-11-22 04:17
May I handle this issue? I love oranges. I can assure a pixel perfect design that matches the provided design and also ensure all wrong URLs are redirected to 404 screen.

**Comment by Aditya-040** [comment] 2024-11-22 04:21
Can I jump on this task? I am new to this project love to contribute.

**Comment by aspiringLilCoder** [comment] 2024-11-22 05:29
Can I jump on this task?

**Comment by System625** [comment] 2024-11-22 05:43
Hey, I would love to work on this

Why Me:
- I've built error handling systems for 2 production React apps
- I have a strong experience with error boundaries and route-based error catching
- I also have a background in design systems implementation

Quick Implementation Plan:
1. Create 404 & global error pages with retry mechanisms
2. Set up route-specific error catchers
3. Implement error logging with debugging context
4. Ensure design consistency & accessibility

Timeline: 3 days total
- Core implementation: 2 days
- Testing & documentation: 1 day

I will include analytics tracking to identify common error patterns and help prevent future issues.

Ready to start immediately and comfortable with iterative feedback.

**Closed** 2024-12-03 00:08 UTC
Labels: good first issue, ODHack10, Frontend
