### ISSUE TITLE
Integration Tests for Land Registry and NFT Interaction

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#83] opened 2024-10-23 08:57 UTC
Task: Create integration tests to ensure proper interaction between the LandRegistry and LandNFT contracts.

Definition of Done:
•  Tests cover the full flow from land registration to NFT minting and transfer.
•  Edge cases in cross-contract interactions are identified and tested.
- Update logic if necessary. 

Note: Only applications through the OnlyDust platform will be considered.

**Comment by CollinsC1O** [comment] 2024-10-24 07:09
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello can I work on this. I'm a frontend and a blockchain developer

**Comment by No-bodyq** [comment] 2024-10-24 07:19
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a full-stack and web3 dev with experience writing tests for smart contracts in cairo. I have contributed to different projects on the only dust platform in the past. Here is my profile: https://app.onlydust.com/u/No-bodyq

### How I plan on tackling this issue
I will inspect the land registry and landNFT contracts to get accustomed to their logic and flow and write unit tests to ensure that they are properly implemented taking into account different edge cases and making corrections if/where necessary in the logic

**Comment by DiegoB1911** [comment] 2024-10-24 07:43
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience. I'm also a member of Dojo Coding, where I'm expanding my expertise in Cairo and Web3 technologies. I'm enthusiastic about learning, and becoming a part of this project.

### How I plan on tackling this issue
To solve this, I will:
1. Understand the interaction between contracts.
2. Plan integration tests.
3. Identify edge cases.
4. Write integration tests.
5. Document the integration tests.

**Comment by blessingbytes** [comment] 2024-10-24 08:40
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello I'm a frontend and blockchain developer. I will love to work on this issue

**Comment by jorgezerpa** [comment] 2024-10-24 10:03
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I'm a fullstack developer with 4 years of experiences building web applications. 
I have a lot of experience with Express, Nextjs, Tailwind...
and also I have nice experience working with Cairo and starknet smart contracts. 
I really like the idea of taking real world assets into the blockchain, so this could be to first of many contributions to these project, I,m very interested in Landver proposal.

### How I plan on tackling this issue
I will work on the file land_registry/src/tests/test_land_register.cairo which already has the basic setup to start writing the tests, including the function to deploy the contracts. 

first, I will modify the deploy_land_registry and deploy_land_nft to trully return the correspondant contracts addresses

I already read carefully the LandRegistry and NFT contracts, I will proceed following the next blueplrint:

### register_land 
- Prepare the params to be sended to the register_land function -> location, area, land_use
- call the register_land function
- Take the returned land_id, and assert that it should be 1 (because it is an incremental key)
- Then I will repeat the process and assert that the land_id should be 2, to confirm to correct functionality of the incremental ids

### get_land
- Call the register_land function to create a new Land
- Take the returned land_id from the register_land function, and pass it as a param in the call to get_land
- Take the response of get_land, and create assert that the location, area and land_use params that was sended on creation, match with the one returned by the get_land function.
- Assert that the caller address is the same than the owner of the returned land
- Finally, I will check the correct emition of tha LandRegistered event

### transfer_land 
- create a land with the register_land function
- Set to addresses, one for the initil owner and other for the new owner to be transfered
- Call transfer_land passing the land_id and new_owner params
- Call get_land to assert that the owner of the land is now the new owner address
- Check the landTransferred event
- Check that the NFT was transfered from old to new owner 
I-  will other test function to test revert cases -> for example, If owner did not own the Land should revert with 'Land not found'

### Update_land 
- check that the call to the update_call function updates the area and land_use values of the Land 
- I will check it by -> asserting the get_land returned Land after update, and asserting the LandUpdated event

### approve_land
- Create a land with the register_land function
- create an inpector calling to add_inspector function (still does not have logic to validate who can add inspectors)
- Use the created inspector to call approve_land and check the success of the mint by asserting the event LandVerified
- Check the correct NFT minting by calling owner_of (from OpenZepellin->erc721 contract) to assert that is owned by the land owner

### reject_land 
- Similiar approach to the approve_land test, but checking the land.is_approved value to be false.

### is_inspector, add_inspector and remove_inspector
- this function has a --> Todo: Add logic to ensure only authorized entities can add inspectors --> so I can create a basic implementation of the test. Of course I saw something related to this in #88 so I will let these ones by last and ask before implement🙌

### Check only_owner and only_inspector functions
- I'll create tests to check that all the function that are only for owners/inspectors reverts when are called from other type of user


I'll be very happy to contribute to the project, I'm attentive. Happy Coding!!🚀🚀

**Comment by ShantelPeters** [comment] 2024-10-24 10:33
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I have extensive experience in smart contract development and testing, particularly with blockchain platforms like Ethereum and StarkNet. My proficiency in programming languages such as Solidity and Rust allows me to build robust smart contracts, including NFT and land management systems. I have successfully implemented various testing strategies, including unit tests and integration tests, ensuring that contracts interact as intended. My background will enable me to effectively create comprehensive integration tests for the LandRegistry and LandNFT contracts, ensuring their seamless functionality and robustness.

### How I plan on tackling this issue
I would begin by thoroughly reviewing the interfaces and functionalities of both the LandRegistry and LandNFT contracts to understand their interactions. Next, I would outline the complete flow to be tested, which includes registering land in the LandRegistry, minting an NFT associated with the registered land, and transferring that NFT to another address.

After configuring a suitable testing framework, such as Hardhat or Truffle, I would develop integration tests that cover each process, ensuring that land registration triggers NFT minting, the NFT is minted with correct attributes, and the transfer functionality updates ownership accurately. I would also verify the internal states of both contracts after each operation for consistency.

I would identify potential edge cases in the interactions, such as minting an NFT for already registered land or transferring an NFT when the sender is not the owner, and implement tests for these scenarios to ensure proper error handling. Throughout this process, I would remain vigilant for any inconsistencies in contract logic and suggest updates as needed to ensure all functions operate as intended. Finally, I would document all test cases, edge cases, and results to provide a clear reference for future development and maintenance.

By following this structured approach, I will ensure that the integration tests comprehensively cover the interactions between the LandRegistry and LandNFT contracts, enhancing the reliability and functionality of the overall system.

**Comment by jorgezerpa** [comment] 2024-10-24 12:38
Hi GM! @fishonamos Thanks for assign me this issue🚀🚀 you added a "Blocked" tag, should I wait for something before start coding?

**Closed** 2024-11-14 17:20 UTC
