### ISSUE TITLE
create inspector lands function 

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#238] opened 2024-12-14 04:02 UTC
Create Function inspector_lands**

- Develop a function to retrieve and manage lands assigned to the inspector.
- Replace Non-Existent Statuses with "Pending":
- Identify and replace all non-existent statuses with "Pending".

- Enhance the update_land function to accept a land_status parameter.

**Comment by ekumamatthew** [comment] 2024-12-14 04:10
I’d love to work on this task.

**Comment by wheval** [comment] 2024-12-14 04:18
Hello @fishonamos, I'm Wheval a Frontend and Cairo Developer.

I’d like to help with this.
I would create a Inspector_lands function that retrieves and manages land assigned to each inspector using Map.
I would replace the state of Non-existent with Pending.
I would modify the update_land function to accept a land_status parameter.
I would compile my code to test for build errors.

Please assign. This would be my first contribution to Landver.
Thank you!

ETA is 1day.

**Comment by Cyberking99** [comment] 2024-12-14 04:22
Hello, I will like to work on this issue.
I will create the inspector_lands function to retrieve and manage the lands assigned to an inspector, then I will replace all the non-existent statuses to "Pending" and add land_status parameter to the update_land function.

My ETA is 8-10 hours

**Comment by MarcusDavidG** [comment] 2024-12-14 04:25
Is it okay if I tackle this?

**Comment by casweeney** [comment] 2024-12-14 04:26
## I Can Handle this issue

## Tackling this issue:
- Giving that I understand how the code base works having contributed to this  code before I will easily create a function signature `inspector_lands()` in an interface.
- I will implement the function to follow the above listed specificaation.
- I will write test for the function to ensure that it works as intended.

## ETA: 10 hours Max

**Comment by fishonamos** [comment] 2024-12-14 04:29
@Cyberking99 @ekumamatthew More issues coming.

**Closed** 2024-12-14 16:53 UTC
Labels: good first issue, help wanted
