### ISSUE TITLE
Add Loading spinner on Action Buttons

### ISSUE THREAD

**Issue by Solomonsolomonsolomon** [NoshonNetworks/landver#250] opened 2024-12-19 05:56 UTC
Currently, some buttons  such as those that perform actions like submitting a form, do not provide feedback to users when clicked. This can lead to confusion or repeated clicks. We need to enhance the user experience by displaying a loading spinner on buttons while an action is being processed.

**Comment by OWK50GA** [comment] 2024-12-19 05:58
Hi, I can handle this.

**Comment by martinvibes** [comment] 2024-12-19 05:59
Hey can I work on this and get it done

**Comment by jahrulezfrancis** [comment] 2024-12-19 06:02
I'd love to make this my first task on LandVer. Here’s my proposed approach to implementing the loading spinner for better user feedback:

Identify Buttons Requiring Feedback: I'll review the existing codebase to locate all buttons that trigger form submissions or perform actions requiring processing time.

Integrate Loading States: For each button, I'll implement a loading state in the component's logic to track when an action is in progress. This state will toggle the spinner visibility.

Update Button Components: I'll modify the button components to display a spinner alongside or in place of the button text during loading. This will involve conditional rendering based on the loading state.

Prevent Repeated Clicks: While the loading state is active, I’ll disable the button to prevent multiple clicks, ensuring smooth processing and avoiding errors.

Test the Enhancements: After implementation, I'll rigorously test all buttons to verify that the loading spinner appears as intended, the buttons are appropriately disabled, and user feedback is clear.

This approach ensures a consistent and intuitive user experience across the application. Please let me know if you have any specific preferences for spinner styles or animations or if there are other actions you'd like prioritized. Thanks

**Comment by GideonBature** [comment] 2024-12-19 06:16
Is it okay if I take this?

My name is Gideon Bature, a Software Engineer. I am proficient writing JavaScript/TypeScript. If assigned this issue, I will send my first PR within 24 hrs.

Thank you!

**Comment by ryzen-xp** [comment] 2024-12-19 06:17
May I handle this issue?

**Comment by olisaagbafor** [comment] 2024-12-19 06:21
Can I tackle this one?

**Comment by 3th-Enjay** [comment] 2024-12-19 06:51
I am a frontend developer and how I understand what needs to be done , how I plan to solve this is simple , once form has been sent to the server I will implement lazy loading and then if response is successful user gets a successful feedback or I it's fails they get the error feedback

**Comment by BigBen-7** [comment] 2024-12-19 06:54
Can I work on this, please?

**Comment by Michaelkingsdev** [comment] 2024-12-19 06:55
@Solomonsolomonsolomon 
I would really love to work on this issue. This is my first time contributing to this amazing project and this Good first issue aligns with my skillset. Thanks

**Comment by Pvsaint** [comment] 2024-12-19 06:56
May I take this task it it's still available? 
I'm Victor,  a front-end and smart contract developer proficient in react js,  next js, solidity and Cairo respectively,  I'll like to contribute to this project, ETA 12hrs.

**Comment by Otaiki1** [comment] 2024-12-21 09:05
Hi @Solomonsolomonsolomon , I am not really clear on the exact buttons to add the loading states too ; I am thinking of adding an optional loading props to the button component , so it makes it easier but i'd still need to know the exact buttons where i will display this prop

**Comment by lifeofrence** [comment] 2024-12-21 13:27
I can implement loading spinners on the buttons to give users feedback while actions are being processed. Let me know if you’d like me to get started.

**Comment by Solomonsolomonsolomon** [comment] 2024-12-21 15:44
@Otaiki1  the modal buttons in /app/client [Proceed to dashboard, connect wallet ,choose wallet]

**Closed** 2024-12-24 14:52 UTC
Labels: good first issue, help wanted, Frontend
